#default application configuration

security:
  user:
    name: "taboo3"
    password: "3oobat"

spring:
  data:
    elasticsearch:
      cluster-name: "taboo3"
      properties:
        path:
          data: "tmpdata/elastic"

